#!/bin/bash

echo

if test -z "$1"
then
  echo "Debes poner el nombre del proyecto (ej miproyecto.local)"
else
  echo "$1"
fi

#TODO check dir exist, contains data...
mkdir $1
cd $1

git init .
git remote add symfony git://github.com/symfony/symfony-standard.git
git fetch symfony
git branch -r
git tag
git checkout master
git merge v2.0.1
bin/vendors install
mkdir -p app/cache
mkdir -p app/logs
rm -rf app/cache/*
rm -rf app/logs/*
sudo chmod +a "_www allow delete,write,append,file_inherit,directory_inherit" app/cache app/logs
sudo chmod +a "jalopez allow delete,write,append,file_inherit,directory_inherit" app/cache app/logs
sudo chmod 777 app/config/parameters.ini

echo '127.0.0.1      '$1 | sudo tee -a /etc/hosts
cat /etc/hosts
open http://"$1"/app_dev.php
mate .

echo 'Siguientes Pasos'
echo 'app/console doctrine:database:create'
