#!/bin/bash

echo "STOP..."
sudo launchctl stop homebrew.mxcl.dnsmasq 
sudo apachectl stop
launchctl unload ~/Library/LaunchAgents/homebrew.mxcl.mysql.plist
	launchctl unload ~/Library/LaunchAgents/homebrew.mxcl.rabbitmq.plist
launchctl unload ~/Library/LaunchAgents/homebrew.mxcl.redis.plist
launchctl unload ~/Library/LaunchAgents/homebrew.mxcl.mongodb.plist
launchctl unload ~/Library/LaunchAgents/homebrew.mxcl.memcached.plist    
sudo postfix stop

sleep 1

echo "START..."
sudo launchctl start homebrew.mxcl.dnsmasq
sudo apachectl start
launchctl load ~/Library/LaunchAgents/homebrew.mxcl.mysql.plist
launchctl load ~/Library/LaunchAgents/homebrew.mxcl.rabbitmq.plist
launchctl load ~/Library/LaunchAgents/homebrew.mxcl.redis.plist
launchctl load ~/Library/LaunchAgents/homebrew.mxcl.mongodb.plist
launchctl load ~/Library/LaunchAgents/homebrew.mxcl.memcached.plist
sudo postfix start